name: event-pipe
main: index.js
version: 0.0.6
description: a simple event pipe, make async easy to use.
author:
  name: 清笃
  email: qingdu@alibaba-inc.com
engines:
  node: '>=0.8.0'
homepage: http://github.com/q3boy/event-pipe
repository:
  type: git
  url: git://github.com/q3boy/event-pipe.git
bugs:
  url: http://github.com/q3boy/event-pipe/issues
devDependencies:
  coffee-script: '*'
  mocha: '*'
  expect.js: '*'
  jscover: '*'
  yamljs: '*'
scripts:
  prepublish: make release
  postpublish: make clean
  test: make test-cov
